### ISSUE TITLE
Active anchor not updating on scroll

### ISSUE THREAD

**Issue by santiRBB** [SnpM/streamlit-scroll-navigation-demo#1]
The active anchor doesn't automatically update. It needs to be clicked to update.

![image](https://github.com/user-attachments/assets/6daf2fd9-6a79-42c7-b082-33561c3d122d)

First, I thought it was a problem after changing the styles, but it doesn't work with the default style.

**Comment by santiRBB** [comment]
It doesn't change if the anchor is selected either. Not even on the demo.

**Comment by nibsbin** [comment]
Do you have a repo or code you can share?

Also which Python, Streamlit, and web browser are you testing with? The demo works for me with Python 3.10, Streamlit 1.39.0, and Chrome browser.

**Comment by santiRBB** [comment]
It´s a problem from Edge, just it out with Chrome and it works perfectly.

**Comment by nibsbin** [comment]
Sweet! I still can't reproduce this problem with Microsoft Edge on my mac, but let me know if this issue disrupts your use case in the future.
